### ISSUE TITLE
Improve the layout of login page

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#112]
We want to have 2 columns:
- left Column: 
 - Title:"Starter Plan"
 - Subtitle: "Log in / Sign In using your Facebook or Google Credentials"
 - Form: 2 buttons 
- right column
 - Title: Publisher Plan
 - Subtitle: Log In using the credentials provided by Librelio
 - Form: 3 text inputs + submit button

The design should be nice, images can be added from the Librelio Home Page

**Comment by deepiksdev** [comment]
No longer needed.
