### ISSUE TITLE
Start implementing rss reader using a paginated list view

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#123]
As a first step, we want to display the title, subtitle, image and beginning of text of each entry. 
The layout should be based on a template similar to the ones used for our csv reader. 
The template should exist in 4 versions: small screen (horizontal & vertical), large screen (horizontal and vertical). Additionally, there should be one template for the first page, and one for the next pages (so, a total of 8 versions will be needed). 
The template should define the number of items displayed, and allow a different layout for each item.

**Comment by deepiksdev** [comment]
No longer needed.
