### ISSUE TITLE
Document template system (tmpl)

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#125]
@serverfire You explained briefly in https://github.com/libreliodev/javascript/issues/91#issuecomment-50732258 the way the template system works, and explained it's used in the pdf reader as well as in the csv reader. We will also use it in the rss reader. 

Since we have not been really successful trying to implement the whole js code inside our mobile apps, what we intend to do is to use tmpl files to generate webviews, using native code. We would like to review this option in detail, and in order to do so, we need to have a better understanding of the template system you implemented:

- are you using a standard library, or specific code?
- can you provide a link to the javascript file(s) where this is implemented?
- can you provide more detailed explanations, either in the code or in the wiki?

**Comment by deepiksdev** [comment]
No longer needed.
