### ISSUE TITLE
In Admin/interstitials, it's not possible to activate new ad

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#135]
![screen shot 2014-10-19 at 17 12 06](https://cloud.githubusercontent.com/assets/3107052/4693586/850cf796-57a2-11e4-99d0-882d314df22b.png)

**Comment by serverfire** [comment]
@libreliodev Fixed.
Now in firefox most admin requests to aws s3 does not have cache.

**Comment by libreliodev** [comment]
Successfully tested
