### ISSUE TITLE
Could not activate publication in admin

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#139]
Earlier this morning, I was not able to activate a publication in prod mode.

@serverfire Any idea of what could happen?

![screen shot 2014-10-24 at 07 57 18](https://cloud.githubusercontent.com/assets/3107052/4766507/8d0c85a8-5b51-11e4-9957-bc42047a3228.png)

**Comment by serverfire** [comment]
@libreliodev Fixed

**Comment by libreliodev** [comment]
@serverfire Still facing the issue:

![screenshot 2015-01-22 14 52 20](https://cloud.githubusercontent.com/assets/3107052/5856763/62f567da-a246-11e4-8fe9-05fdef9674b0.png)

**Comment by serverfire** [comment]
@libreliodev Are you sure you're have latest changes. Because i can't see this error again.
What is the version of safari you're using?

**Comment by libreliodev** [comment]
@serverfire Sorry, there was a problem when updating the code. Successfully tested!
