### ISSUE TITLE
Cannot upload large pdf files using Firefox

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#175]
@serverfire This is a new bug, that may be related to #174. When trying to upload big files with Firefox, the upload stops at a certain percentage, depending on the size of the file and connection quality. A timeout error is shown

![screenshot 2014-12-03 10 43 19](https://cloud.githubusercontent.com/assets/3107052/5278679/623190da-7adc-11e4-8cc9-07d8ecad5b86.png)

**Comment by libreliodev** [comment]
@serverfire Can this urgently be fixed?

**Comment by serverfire** [comment]
@libreliodev Fixed!

**Comment by libreliodev** [comment]
Successfully tested.

Thanks @serverfire
