### ISSUE TITLE
Implement sessionID mechanism for authenticated users management

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#176]
The mechanism originally implemented, storing user name and passwords, is not secure enough for enterprise grade apps.
We need to implement a more secure mechanism, based on session ids. 
The mechanism should be as follows:
- after successful authentication, a session id will be returned (in the header) by subscribers.php: this should be stored in a cookie
- subsequently, this session id should be sent with every request to subscribers.php 

It should also be possible to include the session id in the url by adding `wasession=[SessionID]`

**Comment by libreliodev** [comment]
@serverfire It seems that the credentials are still stored in local storage.

![screenshot 2015-01-03 11 00 46](https://cloud.githubusercontent.com/assets/3107052/5602115/3924ea74-9338-11e4-9f9a-b4a259e4e58a.png)

**Comment by serverfire** [comment]
@libreliodev Localstorage is used for code services. Not user services. Here's the reason why see them.
1. They're exist with using previous version of app earlier. Please delete them and see if they come back.
2. You're still using old version. Please make sure You've the latest version.

**Comment by serverfire** [comment]
@libreliodev Logout should work now. 
Apparently logout.php is not exists in site.

**Comment by libreliodev** [comment]
Successfully tested.
