### ISSUE TITLE
When uploading images from admin, they are resized

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#181]
@serverfire This should of course not be the case

**Comment by libreliodev** [comment]
@serverfire Can this urgently be fixed?

**Comment by serverfire** [comment]
@libreliodev I don't think we have resizing image procedure in app. Where is it?
Do you mean it has been resized in UI?

**Comment by libreliodev** [comment]
@serverfire 

> I don't think we have resizing image procedure in app. Where is it? Do you mean it has been resized in UI?

For some reason, images are resized when uploading.

Here is a screenshot before upload
![screenshot 2015-01-15 21 34 51](https://cloud.githubusercontent.com/assets/3107052/5766038/94faf04e-9cfe-11e4-9f7b-05a7403d90cf.png)

Here a screenshot after upload: the image size has been reduced. 

![screenshot 2015-01-15 21 35 06](https://cloud.githubusercontent.com/assets/3107052/5766048/a6ea5218-9cfe-11e4-8f22-298b57dd564d.png)

This is probably a setting to change with the JS library you've used.

**Comment by serverfire** [comment]
@libreliodev Fixed

**Comment by libreliodev** [comment]
Successfully tested.

Thanks @serverfire.

cc @libreliorip
