### ISSUE TITLE
Implement Google Embed API in analytics pages

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#185]
See https://developers.google.com/analytics/devguides/reporting/embed/v1/

One the user has logged in, use the GA code entered in settings to display the relavant app. If no GA code has been entered, ask the user to enter one.

You will need access to real GA data for testing. Please contact support@librelio.com with your Google account e-mail to get an invitation.

To start with, we want to display the 2 following charts:

![screenshot 2015-01-16 15 43 59](https://cloud.githubusercontent.com/assets/3107052/5778016/182d1228-9d98-11e4-86e1-e8517488eb17.png)

**Comment by serverfire** [comment]
@libreliodev Apparently embed api authentication does not use GACode as it's identifier.
They use OAuth2. For more information see.
https://developers.google.com/analytics/devguides/reporting/embed/v1/component-reference
They call it clientid. 
I think we should create a project in here (https://console.developers.google.com/project)
And clientid with that project. Here's help for creating clientid.
https://developers.google.com/console/help

Thanks

**Comment by libreliodev** [comment]
@serverfire 

> Apparently embed api authentication does not use GACode as it's identifier.
They use OAuth2. For more information see.
https://developers.google.com/analytics/devguides/reporting/embed/v1/component-reference
They call it clientid. 

Yes, sure.

> I think we should create a project in here (https://console.developers.google.com/project)
And clientid with that project. Here's help for creating clientid.
https://developers.google.com/console/help

I don 't think we need to do that.

Please send us privately an e-mail that is registered in Google accounts , and we'll invite you so that you can make a test on https://ga-dev-tools.appspot.com/embed-api/basic-dashboard/, and understand what we want.

**Comment by libreliodev** [comment]
@serverfire Did you finally manage to test  https://ga-dev-tools.appspot.com/embed-api/basic-dashboard/ ?

**Comment by serverfire** [comment]
@libreliodev No i was not able to make this  basic example work. And it's because of these lines.
```
gapi.analytics.auth.authorize({
    container: 'embed-api-auth-container',
    clientid: 'REPLACE WITH YOUR CLIENT ID',
  });
```
I tried to set `clientid` to null and one of the GACode for testing. They made errors at runtime.

**Comment by libreliodev** [comment]
@serverfire Just to make sure we are talking about he same thing, here is how it works for 

- go to  https://ga-dev-tools.appspot.com/embed-api/basic-dashboard/
- click on "Click here to authorize"
-  enter your Google credentials

![screenshot 2015-01-23 15 10 13](https://cloud.githubusercontent.com/assets/3107052/5875878/399682bc-a312-11e4-80fe-6330a73cb0ea.png)

- you should now see a chart

![screenshot 2015-01-23 15 10 57](https://cloud.githubusercontent.com/assets/3107052/5875896/706f66be-a312-11e4-9d28-1631ac6426a8.png)


If it does not work for you this way, please provide screen shots

**Comment by serverfire** [comment]
@libreliodev Yes it does work on that url. 
I wasn't understanding what did you mean.

**Comment by libreliodev** [comment]
@serverfire Great! So now, what you need to do is clear?

**Comment by serverfire** [comment]
Yes it is clear. But i tried to test the same code on my localhost, It doesn't work there.
And the error is about authorization.
`NetworkError: 401 Unauthorized ....`

**Comment by serverfire** [comment]
@libreliodev 
In this site they're using their own clientid. So that's why it's working for them.
We can easily create one clientid for all users. Should i make it?
```
gapi.analytics.ready(function() {

  // Add a state class to the body when auth is successful.
  gapi.analytics.auth.on('success', function() {
    document.body.classList.add('is-authorized');
  });

  // Authorize this user with the client ID in sitemap.yaml
  gapi.analytics.auth.authorize({
    container: 'embed-api-auth-container',
    userInfoLabel: '\u200B',
    clientid: '793177639245-olst43lspv93vkoql0b9l26hmpf9kfmv.apps.googleusercontent.com',
  });
});
```

**Comment by libreliodev** [comment]
@serverfire Our Google `CLIENT ID`for this project is  `1012641315687.apps.googleusercontent.com`.
It is already used for login; see https://github.com/libreliodev/javascript/issues/26#issuecomment-43473656 . Please let me know if it's not working.

**Comment by serverfire** [comment]
@libreliodev 
I'm one step forward. We can login and see that it says you're logged in.
But apparently clientid doesn't made accessing to analytics available.
I get another authorization error.
Cause i get another forbidden error.
```
"NetworkError: 403 Forbidden - https://content.googleapis.com/analytics/v3/management/accountSummaries?max-results=0&embedApiVersion=v1"
```

**Comment by libreliodev** [comment]
@serverfire OK, sorry. This should be OK now.

**Comment by serverfire** [comment]
@libreliodev Please take look at commit 1.
Unfortunately i was not able to find the relevant chart for device models.

**Comment by libreliodev** [comment]
@serverfire OAuth seems to work, but then no chart is displayed

![screenshot 2015-01-24 17 42 01](https://cloud.githubusercontent.com/assets/3107052/5888063/ce338030-a3f0-11e4-882d-c01b2d082807.png)

**Comment by serverfire** [comment]
@libreliodev Please use `All Mobile App Data` GACode. In setup. We should see why this happens.
Do you any errors?

**Comment by libreliodev** [comment]
@serverfire Tried with developer/app2 after entering `All Mobile App Data`. Got the following error.:

![screenshot 2015-01-24 18 06 49](https://cloud.githubusercontent.com/assets/3107052/5888134/deece684-a3f3-11e4-8296-2b177b019315.png)

**Comment by serverfire** [comment]
@libreliodev Please use developer/app1. I had set GACode in it.
Sorry for late answer and misspellings

**Comment by serverfire** [comment]
The domain and protocol of server should be. https://librelio-admin.s3.amazonaws.com/

**Comment by libreliodev** [comment]
@serverfire in Safari, on https://librelio-admin.s3.amazonaws.com/, no chart is displayed

**Comment by serverfire** [comment]
@libreliodev I wasn't aware of css layout that i made. Now it's fixed.
Sorry. I hope i can compensate in future.

**Comment by libreliodev** [comment]
@serverfire This works great, thanks. Please remove the old tracking page, and rename this page tracking (sorry if this was not clear before)

**Comment by serverfire** [comment]
@libreliodev No problem. Renamed to tracking. As requested.

**Comment by libreliodev** [comment]
Successfully tested
