### ISSUE TITLE
In reader, Android and iOS users are not redirected  to native apps

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#189]
See #119.

@serverfire Any idea why?

**Comment by serverfire** [comment]
@libreliodev It's not setup on pdf/csv/tsv reader. Should i add it for these pages?

**Comment by serverfire** [comment]
@libreliodev I'm not sure where do you refer.
Not supported model has two links where follow the pattern in #119 .

**Comment by serverfire** [comment]
![screen shot 2015-02-04 at 1 16 18 pm](https://cloud.githubusercontent.com/assets/132761/6038166/08fc067e-ac70-11e4-95d9-632088d812fc.png)

**Comment by libreliodev** [comment]
@serverfire Sorry, I don't understand your question. Can you elaborate please?

**Comment by serverfire** [comment]
@libreliodev What is the expected behavior? And where it should it?

**Comment by libreliodev** [comment]
@serverfire The expected behavior is the one we already have on index.html

**Comment by libreliodev** [comment]
Successfully tested.
Thanks @serverfire
