### ISSUE TITLE
In admin, create HTML5 page under settings, and make it possible to upload style sheets for covers and pdf reader

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#190]
- The uploaded style sheets, if they exist, should override all other style sheets
- We don't need anymore to define the background color in the "General" settings page: please remove this feature; the default background color should be specified in the css, and be black by default ; however, please do not remove the background image, which should keep being used in Android, iOS, and HTML5

**Comment by libreliodev** [comment]
@serverfire Can you provide the css file you have been using for development for us to test?

**Comment by serverfire** [comment]
@libreliodev In this issue i didn't thought i should provide a test css.
We can talk about it now. Because i didn't did anything in that area.
For now the app accepts css files and inserts it in reader, At appropriate place.

**Comment by libreliodev** [comment]
@serverfire 

> For now the app accepts css files and inserts it in reader, At appropriate place.

Where is it inserted please? Did not you make a test with real CSS?

**Comment by serverfire** [comment]
@libreliodev 
I'll make two test now.
Covers CSS is at: <publisher>/<app>/APP_/Uploads/style_covers.css
PDFReader CSS is at: <publisher>/<app>/APP_/Uploads/style_pdfreader.css

And html5 setup is at: <publisher>/<app>/APP_/Uploads/setup-html5.plist

**Comment by serverfire** [comment]
@libreliodev 
Test for pdfreader. It turns background color to white.
Now we don't have set of rules for making css files. But if you want us to make some rules. We'll do that as part of this issue.
```
.pdfviewer {
  background-color: white;
}
```

**Comment by libreliodev** [comment]
@serverfire 

> Test for pdfreader. It turns background color to white.

I tested with developer/sportguide, but it does not seem to change the background color

**Comment by libreliodev** [comment]
@serverfire 

>> Test for pdfreader. It turns background color to white.

> I tested with developer/sportguide, but it does not seem to change the background color

Sorry, I made a wrong, this works as expected.

Now, please make sure `style_covers.css`overrides the styles on index page (magazines page) of the reader.

**Comment by serverfire** [comment]
@libreliodev Fixed.
developer/wind have css test files uploaded on them.

**Comment by libreliodev** [comment]
@serverfire Great, thanks!
