### ISSUE TITLE
Implement optional header section in covers view of reader

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#191]
We want to have the ability to put the first cover in a header, in a layout similar to the one specified in #168. 

This should be optional, only if the custom css file for covers (see #190) defines a height for the header div. If it does not, then we should just have a regular grid as before, without the first cover appearing larger above.

**Comment by libreliodev** [comment]
@serverfire Can you also provide your css for us to test?

**Comment by serverfire** [comment]
Here's a css example where appears header cover i called it `featured cover`.

```

#featured-cover {
  height: 410px;
}

```

**Comment by libreliodev** [comment]
@serverfire 

I just tested. There may be a misunderstanding here and on #190.

I would expect that after inserting the css  your provided, the first cover would appear big, and there would be a link to the custom css. This is not what's happening. 

![screenshot 2015-02-11 15 55 33](https://cloud.githubusercontent.com/assets/3107052/6149117/c86dbd36-b206-11e4-908e-815fd452b1ac.png)

**Comment by serverfire** [comment]
@libreliodev Description of this issue has not mentioned magazines pages. This is implemented on covers module.

**Comment by libreliodev** [comment]
@serverfire I understand the misunderstandings now. The covers module is not used for the time being. We were talking about the magazines page. That's the reason why we wrote:

> in a layout similar to the one specified in #168

Can this be changed?

**Comment by serverfire** [comment]
@libreliodev Don't worry. I'm please re-write what should i do. Thank you.

**Comment by libreliodev** [comment]
@serverfire Please implement this on the magazines page

**Comment by serverfire** [comment]
@libreliodev Done.

**Comment by serverfire** [comment]
@libreliodev What about publications.html?
Are they also allow to have header?

**Comment by libreliodev** [comment]
@serverfire We do not need this feature for publications.html for the time being.

I understand that the way you implemented this is that the first cover is shown loarger if the stylesheet includes

    #featured-cover {
    display: block;
    }

This is fine.

**Comment by serverfire** [comment]
@libreliodev `display: block;` is more efficient that defining height.
Anyway the script that i wrote supports both. And default stylesheet set the `display` to `none`.
