### ISSUE TITLE
In reader, when clicking on a cover, a modal window should be opened with a description and different buttons

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#193]
The modal view should include:
- a large image of the cover
- a description of the content, populated from the field `Description`in Magazines.plist
- if the user is logged in:
 - a read button
- if the user is not logged in:
 - a sample button
 - depending on the HTML5 settings defined in #192: 0,1 or 2 subscribe buttons

**Comment by libreliodev** [comment]
@serverfire 

This does not seem to be implemented

**Comment by libreliodev** [comment]
@serverfire Please implement this on the magazines page (index.html in reader)

**Comment by serverfire** [comment]
@libreliodev Done. For issues.html

**Comment by libreliodev** [comment]
Successfully tested
