### ISSUE TITLE
In reader, do not show sample button if Magazines.plist contains description

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#194]
Some publishers do not want to provide samples; in this case a `Description`field is added in `Magazines.plist`

**Comment by libreliodev** [comment]
@serverfire This does not seem to be implemented; see for example `wind_386` in `developer/wind`

**Comment by libreliodev** [comment]
@serverfire Please implement this in the magazines page

**Comment by serverfire** [comment]
@libreliodev Works for me. Make sure you are running latest version.
![screen shot 2015-02-11 at 7 04 11 pm](https://cloud.githubusercontent.com/assets/132761/6149847/d6793ac6-b220-11e4-8a06-c17f322c7472.png)

**Comment by libreliodev** [comment]
@serverfire Indeed, sorry about that.
