### ISSUE TITLE
In admin, make it possible to manage multiple publications

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#195]
- replace the `Publications`input defined in #169 by an input with 2 values:
 - `Single` (default)
 - `Multiple`
- create a new page called `issues.html`, with the exact same content as the current `publications.html`
- modify `ìssues.html`as follows:
 - replace `New publication` button by `New issue` button
 - if issues.html was opened with argument issues.html?wapublication=[pubname]:
   -  list the content of the [pubname] folder, instead of listing the root folder
    - when creating a new issue, create a subfolder inside [pubname] 
    - when activating an issue, update `[pubname].plist` instead of `Magazines.plist`
- modify `publications.html`as follows
 - when user clicks on new publication, let user enter folder name, and then only a "generic cover" image 
 - when user has created new publication, create `[pubname]`.plist at the root level
 - when user activates a publication, update `[pubname]`.plist accordingly
 - when user clicks on a folder name, open issues.html?wapublication=[pubname]
- when there is only one publication (as specified in #192), when the user taps on "Publications" on the left menu, open directly `issues.html`

**Comment by serverfire** [comment]
> replace the Publications input defined in #169 by an input with 2 values:
    Single (default)
    Multiple

Is it two radio inputs? What it does?

**Comment by serverfire** [comment]
@libreliodev >when there is only one publication (as specified in #192), when the user taps on "Publications" on the left menu, open directly issues.html

This paragraph is not clear for me.

**Comment by libreliodev** [comment]
@serverfire 

> >replace the Publications input defined in #169 by an input with 2 values:
    Single (default)
    Multiple

> Is it two radio inputs? What it does?

when there is only one publication, when the user taps on "Publications" on the left menu, open directly issues.html

**Comment by libreliodev** [comment]
@serverfire 

>> when there is only one publication (as specified in #192), when the user taps on "Publications" on the left menu, open directly issues.html

> This paragraph is not clear for me.

Forget the "(as specified in #192)". The idea is that either there is only one publication, and in this case it is not needed to display the publications.html page, or there are multiple publications, and in this case we need to display this page

**Comment by serverfire** [comment]
@libreliodev Why wont we place `[pubname].plist` file inside its folder. This helps easing implementation.
I don't think it would cause any problem in app.
What do you think?

**Comment by libreliodev** [comment]
@serverfire 

> Why wont we place `[pubname].plist` file inside its folder. This helps in implementation.
I don't think it would cause any problem in app.

There are some legacy issues here, but it's OK, let's follow your suggestion. Thanks.

**Comment by libreliodev** [comment]
@serverfire 

> Replace the Publications input defined in #169 by an input with 2 values: ...

This does not seem to be implemented

**Comment by serverfire** [comment]
@libreliodev 
Look. Publications with select of single or multiple.
![screen shot 2015-02-11 at 7 00 15 pm](https://cloud.githubusercontent.com/assets/132761/6149756/42cacff6-b220-11e4-90d5-7c68339b7d6c.png)

**Comment by libreliodev** [comment]
Successfully tested
