### ISSUE TITLE
In reader, create publications.html and issues.html

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#196]
- duplicate the existing `index.html` to create both `publications.html` and `issues.html`
- modify ìssues.html`as follows:
 - if `issues.html`was opened with argument wapublication=[pubname] , display covers specified by `[pubname].plist`instead of `Magazines.plist`
- modify `publications.html`as follows
 - do not display any button, just display the generic cover
 - when clicking on a cover, open `ìssues.html?wapublication=[pubname]`
- modify `index.html`as follows
 - by default, or if there is only one publication, load `ìssues.html`
 - if there are multiple publications, load `publications.html`

**Comment by libreliodev** [comment]
@serverfire 

> by default, or if there is only one publication, load ìssues.html

This does not seem to be implemented

**Comment by serverfire** [comment]
@libreliodev I believe #196 & #195 are implemented right. Please re-check. In the meantime I'll work on magazines page.

**Comment by libreliodev** [comment]
Successfully tested
