### ISSUE TITLE
In admin, it's not possible to deactivate the first publication

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#197]
Clicking on the `Active` button does not deactivate the publication as it did previously (cf #10)

@serverfire Can you fix this?

**Comment by serverfire** [comment]
@libreliodev I can deactivate publication in FF.
Which app you're trying to deactivate?
What version of FF?

**Comment by libreliodev** [comment]
@serverfire Thanks for looking into this quickly. After further investigation:

- the problem is not limited to Firefox, it also exists with Safari
- it seems that it happens only with the first publication; for example trying to deactivate wind in developer/sportguide does not seem to be possible

**Comment by serverfire** [comment]
@libreliodev Fixed.

**Comment by libreliodev** [comment]
@serverfire Thanks.
