### ISSUE TITLE
In pdf reader, some pdf files are not displayed properly, whereas they look fine in the Firefox pdf reader

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#200]
@serverfire See for example testcg in developer/app1. There is a black area instead of text. Could this be because we are not using the latest pdf.js version?

**Comment by serverfire** [comment]
@libreliodev Yes it is.
I'm porting the project for pdf.js new version.
Hopefully there is not to much changes in new pdf.js API.

**Comment by libreliodev** [comment]
@serverfire OK, let's cross fingers

**Comment by serverfire** [comment]
@libreliodev Strange, testcg is no longer exist in developer/app1?

**Comment by serverfire** [comment]
@libreliodev Hi.
This comment is not related to this issue.
Issues between 189 and 200 are implemented.
You can test them now.
Publications/Issues section may have problems, I tried to make it bug free, But nothing is perfect.
Please use `bower install` before running grunt.

Thank you

**Comment by libreliodev** [comment]
Successfully tested.
