### ISSUE TITLE
It's no longer possible to open directly pdf in reader when providing wasession

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#205]
According to #176, this URL should work: `http://reader.librelio.com/pdfreader.html?wapublisher=wolterskluwer&waapp=franceroutes&waurl=/fr394_20150101/fr394_20150101_.pdf&wasession=PHPSESSID_PHPSESSID_53hhbnmn11a6dqcfil16pdd7g0`but it does not.

Our records indicate that subscribers.php is not even called.

@serverfire Can you fix this very urgently?

**Comment by serverfire** [comment]
@libreliodev Is this session id is working now?
I saw app get response from request to subscribers.php with access denied error.

**Comment by serverfire** [comment]
Sorry power went down in here.

**Comment by libreliodev** [comment]
@serverfire 

Thank you for your quick feedback.

Here is a session id that should work now: `v1sje9asapopv77pc3194krs00`

**Comment by serverfire** [comment]
This is curl of the request. Response is "not authorized".
`curl 'http://download.librelio.com/downloads/subscribers.php?client=wolterskluwer&app=franceroutes&service=WoltersKluwer&urlstring=%2Ffr394_20150101%2Ffr394_20150101_.pdf&deviceid=3537223275&header=200&wasession=v1sje9asapopv77pc3194krs00' -H 'Host: download.librelio.com' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0' -H 'Accept: application/xml, text/xml, */*; q=0.01' -H 'Accept-Language: en-us,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Referer: http://localhost/libreliodev/dist/reader/pdfreader.html?wapublisher=wolterskluwer&waapp=franceroutes&waurl=/fr394_20150101/fr394_20150101_.pdf&wasession=v1sje9asapopv77pc3194krs00' -H 'Origin: http://localhost' -H 'Cookie: PHPSESSID=53hhbnmn11a6dqcfil16pdd7g0; _ga=GA1.2.1505419013.1423396606'`

**Comment by serverfire** [comment]
@libreliodev Response is this.
```
<?xml version="1.0" encoding="UTF-8"?>
			<Error>
			<Code>Unauthorized device</Code>
			<Message>Unauthorized Device</Message>
			<UrlString>/fr394_20150101/fr394_20150101_.pdf</UrlString>

			</Error>
```

**Comment by libreliodev** [comment]
@serverfire Sorry, this was due to a security limitation, we have reset the limit.

**Comment by serverfire** [comment]
@libreliodev 
Now i get LoginFailed.
```
<?xml version="1.0" encoding="UTF-8"?>
			<Error>
			<Code>LoginFailed</Code>
			<Message>Login Failed</Message>
			<UrlString>/fr394_20150101/fr394_20150101_.pdf</UrlString>

			</Error>
```

**Comment by libreliodev** [comment]
@serverfire Thanks, we'll see that tomorrow.

**Comment by libreliodev** [comment]
@serverfire Session id `v1sje9asapopv77pc3194krs00` expiry date has been reactivated for 24 hours, so you should be able to use it again; Be aware that after you use it for the fist time, it will expire 15 minutes later unless you keep it active. Don't hesitate to ask me if you need me to reactivate it again.

**Comment by serverfire** [comment]
@libreliodev It is working for me.
1. Maybe they're using the old version of project.
2. In what browser they have problem?

**Comment by libreliodev** [comment]
@serverfire Indeed, it's working. The issue is probably related to session expiration. Sorry for disturbing you with it, and thanks again.
