### ISSUE TITLE
Implement Pivottable.js in reader and admin

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#206]
In order to do this, we need to:
- create dependancies between this project and Pivottable.js on Github
- create a new reader page called `tablereader.html`, that will use the same arguments as pdfreader and others (`waapp`, `wapublisher`, `waurl`). Based on these arguments, the page should display a pivot table with the csv file specified by `waapp`, `wapublisher` and `waurl`, in a similar way as [this page](http://nicolas.kruchten.com/pivottable/examples/local.html) does after choosing a csv file
- create a new admin page called pivots.html, which will display a pivot table with the contents of [publisher]/[app]/APP_/REPORTS/publications_.csv

**Comment by serverfire** [comment]
@libreliodev Done

**Comment by libreliodev** [comment]
Successfully tested.
