### ISSUE TITLE
Implement server side authorization for Google Analytics

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#207]
In order to do this, we need to:
- create an `authorizations.html`page in admin
- from this page, if no refresh token exists in [publisher]/[app]/APP_/Uploads/authorizations_.plist, have the user generate one using a php page (that needs to be coded, as part of this issue, using Google Analytics SDK)
- store the token in  in [publisher]/[app]/APP_/Uploads/authorizations_.plist

**Comment by serverfire** [comment]
@libreliodev I was able to test fetching refresh_token.
Now we can discuss the issue in more details.
Please check.
`refresh_token is return only the first time user gives access to the app`

**Comment by libreliodev** [comment]
Refresh token needs to be stored in authorizations_.plist

**Comment by serverfire** [comment]
@libreliodev It's going to store there.
But the system is not working well now. I'll work on that.

**Comment by serverfire** [comment]
@libreliodev Things are working well now. Can you test it?
I'm open to do changes in UI and other parts of this issue without extra charge.
Sorry for delay.

**Comment by serverfire** [comment]
@libreliodev You can use `http://localhost/...` for testing. Or if you want to change it. You can change the url in file `src/admin_assets/js/pages/authorizations.js` at line 6 and 7.

**Comment by libreliodev** [comment]
@serverfire Successfully tested.

Before we close this issue, can you make a distinction between the origin host (where the console js+html file will be hosted) and the backend (where the php files are stored)?

The origin host should be entered as a variable in the code, it should be obtained via javascript. The backend host will be a different one, and should be entered as a variable in the code.

Thanks.

**Comment by serverfire** [comment]
@libreliodev 
I stored backend url in config file and since script is running on origin host We don't need to store it in config file.
Also it's not used in this issue.

Thank you.
