### ISSUE TITLE
In Firefox, in admin, localized version is sometimes not displayed

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#208]
This has been reported by @rhanot . We need to investigate further to make sure it's a bug, related to #49. 

@rhanot Can you make sure your Firefox version is not configured to display english contents in priority?

![screenshot 2015-02-17 19 31 24](https://cloud.githubusercontent.com/assets/3107052/6234570/1913ca76-b6dc-11e4-8ba7-fcc59047d3a7.png)

cc @serverfire

**Comment by serverfire** [comment]
@libreliodev I don't understand.

**Comment by libreliodev** [comment]
@serverfire 

> I don't understand.

.@rhanot reported that the interface was in english, whereas he is using a french system. We need to understand why. Let's wait for his feedback regarding his Firefox configuration, then we'll investigate more if necessary.

**Comment by serverfire** [comment]
@libreliodev Thank you

**Comment by rhanot** [comment]
@libreliodev: my Firefox configuration
![contenu](https://cloud.githubusercontent.com/assets/8896755/6273101/028a8c8a-b86d-11e4-9bf0-b35c60eb5c38.jpg)

**Comment by serverfire** [comment]
@libreliodev A quick fix can be aliasing fr to fr-fr.

**Comment by libreliodev** [comment]
@rhanot Thanks a lot for the screenshot, very helpful. Please do not close issues as long as they are not fixed.

@serverfire I also suspect the reason of the bug is that French localization is only activated with fr-fr, not fr. Can you go ahead with the quick fix?

**Comment by serverfire** [comment]
@libreliodev Fixed!

**Comment by libreliodev** [comment]
Thanks @serverfire 

@rhanot Can you test again please?

**Comment by rhanot** [comment]
still in English ...

**Comment by libreliodev** [comment]
Thanks @rhanot. Maybe a caching issue. We'll double check and keep you posted.

**Comment by libreliodev** [comment]
@rhanot We have double checked, and the bug does seem to be fixed. See screenshot below.
Can you make sure you have refreshed the page? Also, can you look at the menu titles at the left? The welcome message may still be in English, as it has not been translated (the translations will be updated shortly), but the menus should be in French. Thanks again for your help.

cc @serverfire 

![screenshot 2015-02-21 07 01 35](https://cloud.githubusercontent.com/assets/3107052/6313042/dffa7bae-b997-11e4-8800-7002fb957cab.png)

**Comment by rhanot** [comment]
OK UI is in french

**Comment by libreliodev** [comment]
Many thanks @rhanot.
