### ISSUE TITLE
In admin, filters do no work when using pivottable.js

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#209]
This is related to #206 

With the regular version of pivottable.js, for instance on http://nicolas.kruchten.com/pivottable/examples/mps_agg.html , when you select the dropdown menu for a dimension  (for example Province), you get the possibility the select some values and filter results.

You don't have such a possibility on the version that we have, for example on pivot.html: the dropdown menus are not active.

@serverfire Can you fix this?

**Comment by serverfire** [comment]
@libreliodev I fixed it.
Part of bugfix was for pivottable project.
So i have listed dist files for pivottable below. Please copy them in `./bower_components/pivottable/dist/` for now.
I'll also send a pull request for fixing this bug on pivottable project. 
Thank you

- https://www.dropbox.com/s/uzw95vkkzjf7ib0/pivot.min.css?dl=0
- https://www.dropbox.com/s/9x9w9931nzyksvo/pivot.min.js?dl=0

**Comment by libreliodev** [comment]
Source code of fixes has been saved in https://gist.github.com/libreliodev/14444a9a3955f801977c

**Comment by libreliodev** [comment]
Successfully tested.
Many thanks @serverfire
