### ISSUE TITLE
Compile error while ussing $ grunt.

### ISSUE THREAD

**Issue by marini21** [libreliodev/javascript#217]
src/language/en-Us/admin.po 
warn: spawn unkown use -- force continue.
Fail  grunt fail to compile

**Comment by libreliodev** [comment]
@serverfire Any idea why?

**Comment by serverfire** [comment]
@libreliodev Having python is necessary. Make sure you have python. In /usr/bin/python

**Comment by libreliodev** [comment]
@marini21 Make sure you have python. In /usr/bin/python (thanks @serverfire )
