### ISSUE TITLE
The command open index.html

### ISSUE THREAD

**Issue by ebongfrank** [libreliodev/javascript#220]
The command open index.html isn't working for me, I obtain this error: open : The term 'open' is not recognized as the name of a cmdlet, function, script file, or operable program.

**Comment by avittecoqDAJ** [comment]
Hello,

Could you give us more details on what you are trying to do, and how ?

**Comment by ebongfrank** [comment]
I am trying to build the Libreliodev Java script

**Comment by ebongfrank** [comment]
$ git clone https://github.com/libreliodev/javascript.git yourfoldername
$ cd yourfoldername
$ git submodule init
$ git submodule update
$ npm install
$ bower install 
$ grunt 
$ cd dist/
$ open index.html

The last step the "open index.html" gives me this error: The term 'open' is not recognized as the name of a cmdlet, function, script file, or operable program.

**Comment by avittecoqDAJ** [comment]
Hello,

The open command means that you have to open the website hosted on your server from your browser.

Best regards

**Comment by ebongfrank** [comment]
Unfortunately the command is sending an error

**Comment by avittecoqDAJ** [comment]
It's because it's not a command. You just have to open the index.html file with your browser
