### ISSUE TITLE
Admin console login

### ISSUE THREAD

**Issue by garshom** [libreliodev/javascript#223]
I have compiled the javascript and I can't login to admin console,  are there default login credentials and you share them to me.

**Comment by avittecoqDAJ** [comment]
Hello @garshom,

Did you link your admin console to your Amazon AWS account ?
The credentials are the key provided by amazon.

Best regards

**Comment by garshom** [comment]
Hello Avittecoq, 

In have tried to like it to my aws account but there is confusion in the paremeters in the config.json file,  could you please let me which parameter in the config.json file what it corresponds with in the aws credentials,  I need serious help on this guys .

**Comment by garshom** [comment]
Hello Avittecoq, 

I have tried to link it to my aws account but there is confusion in the paremeters in the config.json file,  could you please let me know which parameters in the config.json file and what they correspond with in the aws credentials,  I need serious help on this guys .
