### ISSUE TITLE
how to linking admin console with aws account 

### ISSUE THREAD

**Issue by garshom** [libreliodev/javascript#224]
How could I link the admin console with my aws account ? , i have the console running on aws at https://d1gh2g8d1g3492.cloudfront.net   but am a bit confused with the parameters listed in the  config.JSON file as below 

{
    "storageAuthKey": "librelio-auth",
    "s3Bucket": "librelio-europe",
    "s3BucketRegion": "eu-west-1",
    "storageAppNameKey": "librelio-app",
    "singleAppModeKey": "librelio-sappmode",
    "awsExpireReverseInHours": 72,
    "idFedDefaultApp": "app1",
    "idFedFBUserDirnamePrefix": "fb_",
    "idFedGPUserDirnamePrefix": "gp_",
    "idFedFBAppId": "201544626555225",
    "idFedFBUsersRoleArn": "arn:aws:iam::105216790221:role/RoleForFacebook",
    "idFedGPUsersRoleArn": "arn:aws:iam::105216790221:role/RoleForGoogle",
    "GoogleClientId": "1012641315687.apps.googleusercontent.com",
    "backendUrl": "http://localhost/libreliodev-php",
    "locale": "en-US"
}

Could someone help and clarify or highlight on each of those params in the config.JSON file ?

Thanks.

**Comment by avittecoqDAJ** [comment]
Hello Garshom,

You have to set the 5 firsts line of your config file according to the value you get from Amazon Web Service configuration.

Best regards,

**Comment by garshom** [comment]
Could you please clarify  on which values from aws speficically,  because from my aws I have with me access key,  secret key,  bucket name, bucket region.

**Comment by avittecoqDAJ** [comment]
Hello Garshom,

I made a mistake.
Actually you just need to set the bucket name (from your s3 setting).
The rest will be set during the login.
During the logging you have to input your AWS access key and private key of the user who has right for the s3 server.
The third input in one of the directory contained by the s3 bucket.

Best regards,
