### ISSUE TITLE
Not able to save anything in the Librelio admin console GUI

### ISSUE THREAD

**Issue by garshom** [libreliodev/javascript#226]
Hello Team, 

I have managed to link the admin console with my aws account but there is nothing I can do in the admin console GUI,  no saving buttons, and also cannot setup an application not even able to create users and publication.

Could you please advise on what could be wrong on my side.

Thanks.

**Comment by avittecoqDAJ** [comment]
Hello,

Did you build an mobile application ?
If yes let's say that the package name used during the build is com.mycompany.myapp.
Then you should have in your s3 bucket a folder "mycompany" containing another folder "myapp".

Regards

**Comment by garshom** [comment]
Hello,  

I have not yet compiled the mobile apps yet ,  but Idealy I think before compiling the apps, I should be able to create an application,  create users within the admin console which is failing as of now. 

Could you please advise what can be done for me to be able to create applications and users within the admin console. 

Thanks

**Comment by garshom** [comment]
I have made the changes and tried adding the application folder as directed but currently getting below aws error  "InvalidArgument: Requests specifying Server side Encryption with AWS KMS managed keys require AWS signature version 4" . 
could advise on the could be missconfiguration on my side

Thanks

**Comment by avittecoqDAJ** [comment]
Hello,

This is an AWS error. Please check your aws configuration.
Maybe the AWS Key you use doesn't have the correct configuration.

Regards

**Comment by garshom** [comment]
Hello, 

I can now create application in the admin console,  could you please advise on the dynamodb table schema that I need to create in my aws account. 

Thanks

**Comment by avittecoqDAJ** [comment]
Hello,

You need a Table "Users" with the following fields:
'App' (string)
'User Name' (string)
' Password' (string)
'Status' (int)

Regards,

**Comment by garshom** [comment]
thanks,  this is now working fine.

But one more challenge in this regard,  within my preview  in the admin console,  the preview is still pointing to //reader. librelio.com. could you please advise on how to change this such that it point to my reader URL. 

Thanks.

**Comment by avittecoqDAJ** [comment]
Hello,

Unfortunatelly this is a problem in our code, you'll have to change it in your code.
Feel free to contribute your improvement of the code.

Regards
